### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by luser** [mrahtz/javascript-karplus-strong#2]
I'm interested in using this code in another project but it's currently lacking a software license. Could you add one to the project? Something simple like a BSD license would be great.

**Comment by mrahtz** [comment]
I've deliberately left it without a license for the time being, since it was reverse engineered from André's work (which was further developed into a commercial tool), and I haven't been able to get in contact with him to check how he'd feel about it being used in other projects.

Sorry not to be of more help :(

**Comment by luser** [comment]
Bummer. I finished up what I was playing with and published it anyway:
http://luser.github.io/javascript-karplus-strong/

It's too bad, this is the nicest JS guitar synth I've found!

**Comment by mrahtz** [comment]
Hohhh that's actually really cool!

Tell you what - I'll try sending André another email. Maybe they just got lost in a flood last time.

**Comment by mrahtz** [comment]
Still no word from André :( so I'm going to leave it license-less for now.
